### ISSUE TITLE
Módulo BrazilCustomerAttributes

### ISSUE THREAD

**Issue by eduardoddias** [magento-developers-brasil/Brazilian-Solutions#6]
**Descreva o módulo que você gostaria de sugerir**
https://github.com/eduardoddias/Magento-SystemCode_BrazilCustomerAttributes

**É uma integração com algum serviço?**
Não

**Esse módulo vai afetar quais áreas Magento**
- [X] Frontend
- [X] Painel Administrativo
- [ ] Crontabs
- [ ] Command Line
- [ ] API Rest
- [ ] GraphQL

**Esse módulo vai afetar quais partes do Magento**
- [ ] CMS (Home, Landing Pages, etc)
- [X] Página Carrinho
- [X] Página Checkout
- [ ] Página de Produtos
- [ ] Página de Categorias
- [ ] Página de Buscas
- [X] Outros? Quais?
Front: Cadastro, meus endereços e meus dados
Back: Configurações, pedidos e clientes

**Este módulo é uma melhoria para o Magento?**
Adapta campos do cliente e seu endereço para o mercado brasileiro.

**Já existe um módulo que faça algo parecido?**
https://github.com/eduardoddias/Magento-SystemCode_BrazilCustomerAttributes

**Comment by tiagosampaio** [comment]
Obrigado, pela sua contribuição, @eduardoddias.

O módulo foi incluído como referência no repositório.

https://github.com/magento-developers-brasil/brazilian-solutions/blob/master/docs/CUSTOMER_MODULES.md

Abraços.

\- Tiago
